[build-system]
requires = ["scikit-build-core>=0.5", "setuptools"]
build-backend = "scikit_build_core.build"

##################################################################
##################################################################

[project]
name = "ffpopt"
version = "1.1.0"
description = "force field parameter optimizer"
requires-python = ">=3.8"
authors = [
  {name = "Timothy J. Giese", email = "TimothyJGiese@gmail.com"},
  {name = "Zeke Piskulich", email = "piskulichz@gmail.com"}
]
# license = {file = "LICENSE"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Development Status :: 5 - Production/Stable",
]

# GPU-enabled
# --extra-index-url https://download.pytorch.org/whl/cu121
# CPU-only:
# --extra-index-url https://download.pytorch.org

dependencies = [
    'scipy',
    'matplotlib',
    'numpy<2',
    'ndfes'
# INSTALLED VIA CONDA
#   ,geometric
#   ,ase
]

[dependency-groups]
pytorch = [
    'torch',
    'torchvision',
    'torchaudio',
    'torchdata>=0.8.0,<=0.9.0',
    'cuequivariance',
    'cuequivariance-torch',
    'cuequivariance-ops-torch-cu12',
    'mace-torch',
    'torchani', 
    'aimnet[ase] @ git+https://github.com/isayevlab/aimnetcentral.git',
    #'aimnet2calc @ git@https://github.com/zubatyuk/aimnet2calc',
    'fennol[cuda]',
    'torchmd-net',
    'deepmd-kit[torch]',
    'orb-models',
    'dgl',
    'espaloma_charge'
]
tensorflow = [
    'tensorflow[and-cuda]',
    'deepmd-kit[tf]'
]
fairchem = [
    'fairchem-core @ git+https://github.com/facebookresearch/fairchem.git#subdirectory=packages/fairchem-core',
    'huggingface_hub'
]


# readme = "README.md"
keywords = ["machine learning models"]


##################################################################
##################################################################

[project.urls]
repository = "https://gitlab.com/RutgersLBSR/ffpopt"

##################################################################
##################################################################

[tool.scikit-build]
# This tells scikit-build where to find your python package code
# so it can merge the CMake output into it

wheel.packages = { "ffpopt" = "src/python/lib/ffpopt", "ffpopt/bin" = "src/python/bin" }

wheel.install-dir = "."

wheel.py-api = "py3"

sdist.include = ["src/python/lib/ffpopt/**/*",
                 "src/python/bin/**/*",
		 "CMakeLists.txt"]


[tool.scikit-build.cmake.define]
# This replaces the tool.scikit-build.cmake.options section
#ACADEMIC = "OFF"
FFPOPTVERSION = "1.1.0"

##################################################################
##################################################################

[project.scripts]
# Creates the command 'ffpopt-wrapper' in PREFIX/bin/
"ffpopt-DihedScan.py" = "ffpopt.scripts:ffpopt_DihedScan"
"ffpopt-Optimize.py" = "ffpopt.scripts:ffpopt_Optimize"
"ffpopt-GenDihedFit.py" = "ffpopt.scripts:ffpopt_GenDihedFit"
"ffpopt-DihedTwistWorkflow.py" = "ffpopt.scripts:ffpopt_DihedTwistWorkflow"
"ffpopt-DihedWavefront.py" = "ffpopt.scripts:ffpopt_DihedWavefront"
"ffpopt-ConfSearch.py" = "ffpopt.scripts:ffpopt_ConfSearch"
"ffpopt-RespFit.py" = "ffpopt.scripts:ffpopt_RespFit"
"ffpopt-DeltaRespFit.py" = "ffpopt.scripts:ffpopt_DeltaRespFit"
"ffpopt-CpeFit.py" = "ffpopt.scripts:ffpopt_CpeFit"
"ffpopt-WavefrontToDP.py" = "ffpopt.scripts:ffpopt_WavefrontToDP"
"ffpopt-WavefrontAnimate.py" = "ffpopt.scripts:ffpopt_WavefrontAnimate"
"ffpopt-DihedTwistAnimate.py" = "ffpopt.scripts:ffpopt_DihedTwistAnimate"
"ffpopt-xyz2mol2.py" = "ffpopt.scripts:ffpopt_xyz2mol2"
"ffpopt-PrepareInput.py" = "ffpopt.scripts:ffpopt_PrepareInput"
"ffpopt-Json2Crds.py" = "ffpopt.scripts:ffpopt_Json2Crds"
"ffpopt-JsonJoin.py" = "ffpopt.scripts:ffpopt_JsonJoin"
"ffpopt-JsonSplit.py" = "ffpopt.scripts:ffpopt_JsonSplit"
"ffpopt-Json2Img.py" = "ffpopt.scripts:ffpopt_Json2Img"
"ffpopt-FindSugarPuckers.py" = "ffpopt.scripts:ffpopt_FindSugarPuckers"
"ffpopt-NDimWavefront.py" = "ffpopt.scripts:ffpopt_NDimWavefront"
"ffpopt-DeltaPuckerFit.py" = "ffpopt.scripts:ffpopt_DeltaPuckerFit"
