def write_amber_restart(coords, fh, title="Generated by Python"):
    """
    Writes a (Natom, 3) numpy array to an Amber ASCII restart file.
    Format: 2 lines of header followed by coordinates in 6F12.7 format.
    """
    n_atoms = coords.shape[0]
    
    # Flatten coordinates to a 1D array (X1, Y1, Z1, X2, Y2, Z2, ...)
    flat_coords = coords.flatten()

    if True:
        # Line 1: Title (limit to 80 chars)
        fh.write(f"{title[:80]}\n")
        
        # Line 2: Number of atoms (right-justified) and optional time
        # Standard format often uses I5 or I6 for atom count
        fh.write(f"{n_atoms:5d}\n")
        
        # Lines 3+: Coordinates in 6F12.7 format (6 numbers per line, 12 chars each)
        for i in range(0, len(flat_coords), 6):
            chunk = flat_coords[i:i+6]
            line = "".join(f"{val:12.7f}" for val in chunk)
            fh.write(line + "\n")


            

class Struct(object):
    
    def __init__(self,data):
        from copy import deepcopy
        from . Restraints import RestraintList
        from . Constraints import ConstraintList
        
        self.data = deepcopy( data )
        self.restraints = None
        if "restraints" in self.data:
            if self.data["restraints"] is not None:
                self.restraints = RestraintList.from_list_of_dict\
                    ( self.data["restraints"] )
        self.constraints = None
        if "constraints" in self.data:
            if self.data["constraints"] is not None:
                self.constraints = ConstraintList.from_list_of_dict\
                    ( self.data["constraints"] )
                
        self.graph = None

        if "resnames" in self.data:
            resnames = {int(k): v for k, v in self.data["resnames"].items()}
            self.data["resnames"] = resnames
        else:
            self.data["resnames"] = {0: "MOL"}
            
        if "residxs" not in self.data:
            self.data["residxs"] = [0]*len(self.data["elements"])

    @classmethod
    def from_parmed(cls,mol):
        from . constants import GetAtomicSymbol
        from collections import defaultdict as ddict
        data = {}
        data["positions"] = []
        data["names"] = []
        data["types"] = []
        data["elements"] = []
        data["charges"] = []
        data["residxs"] = []
        resnames = ddict(str)
        q = 0
        for a in mol.atoms:
            data["positions"].append( [a.xx,a.xy,a.xz] )
            data["names"].append(a.name)
            data["types"].append(a.type)
            data["elements"].append( GetAtomicSymbol(a.element) )
            data["charges"].append(a.charge)
            data["residxs"].append(a.residue.idx)
            resnames[a.residue.idx] = a.residue.name
            q += a.charge
        data["resnames"] = dict(resnames)
        data["spin"] = 1
        #data["charge"] = int(round(q))
        data["bonds"] = []
        for x in mol.bonds:
            data["bonds"].append( [x.atom1.idx, x.atom2.idx ] )
        data["parm"] = None
        data["constraints"] = []
        data["restraints"] = []
        data["name"] = "s000"
        data["energy"] = None
        data["forces"] = None
        
        from collections import defaultdict as ddict
        names = data["names"]
        seen = ddict(int)
        for iname in range(len(names)):
            name = names[iname]
            if name in seen:
                for i in range(98):
                    j=i+1
                    tname = "%s%i"%(name,j)
                    if tname in seen or tname in names:
                        continue
                    else:
                        break
                seen[tname] += 1
                names[iname] = tname
        data["names"] = names
        
        return cls(data)

    
    @classmethod
    def from_mol2(cls,fname):
        from . Reader import ReadMol2
        import parmed
        
        mol = ReadMol2(fname)
        
        for a in mol.atoms:
            if isinstance(a.type,int):
                for elem,num in parmed.periodic_table.AtomicNum.items():
                    if num == a.atomic_number:
                        a.type = elem
                        break
        return cls.from_parmed(mol)

    
    @classmethod
    def from_parm(cls,parm7,rst7):
        import parmed
        mol = parmed.load_file(parm7,xyz=rst7)
        return cls.from_parmed(mol)

    @classmethod
    def from_rdkit(cls,mol):
        import numpy as np
        from collections import defaultdict as ddict
        from rdkit import Chem
        from rdkit.Chem import AllChem
        
        eles = [atom.GetSymbol() for atom in mol.GetAtoms()]
        try:
            conf = mol.GetConformer()
        except:
            status = AllChem.EmbedMolecule(mol, randomSeed=42)
            conf = mol.GetConformer()

        coords = conf.GetPositions()
        net_charge = Chem.GetFormalCharge(mol)
        qs = [net_charge/len(eles)]*len(eles)
        bonds = [(bond.GetBeginAtomIdx(), bond.GetEndAtomIdx()) for bond in mol.GetBonds()]
        data = {}
        data["positions"] = coords.tolist()
        data["names"] = eles
        data["types"] = eles
        data["elements"] = eles
        data["charges"] = qs

        resnames = ddict(str)
        residxs = []
        for atom in mol.GetAtoms():
            res_info = atom.GetPDBResidueInfo()
            if res_info:
                idx = res_info.GetResidueIndex()
                residxs.append( idx )
                resnames[idx] = res_info.GetResidueName()
            else:
                residxs.append(0)
                resnames[0] = "MOL"
        data["residxs"] = residxs
        data["resnames"] = dict(resnames)
        data["spin"] = 1
        #data["charge"] = int(round(net_charge))
        data["bonds"] = bonds
        data["parm"] = None
        data["constraints"] = []
        data["restraints"] = []
        data["name"] = "s000"
        data["energy"] = None
        data["forces"] = None

        return cls(data)


    def GetCrds(self):
        """Return N,3 numpy array copy of coordinates in Angstrom"""
        import numpy as np
        return np.array(self.data["positions"])

    
    def GetAtomicNumbers(self):
        """Return a list of integer atomic numbers"""
        from . constants import GetAtomicNumber
        return [ GetAtomicNumber(e) for e in self.data["elements"] ]

    
    def GetCharge(self):
        """Return the 'charge' value from the internal data structure"""
        return int(round(sum(self.data["charges"])))

    
    def ReadAmberParm(self):
        """
        Read an amber parm7 file from disk

        Parameters
        ----------
        None
        
        Returns
        -------
        mol : parmed Structure object
        """
        
        from pathlib import Path
        import parmed
        import os
        from tempfile import mkstemp

        name = self.data["name"]
        if "parm" not in self.data:
            raise Exception(f"Key 'parm' not in structure '{name}'")
        pfile = self.data["parm"]
        if pfile is None:
            raise Exception(f"Key 'parm' is None in structure '{name}'")
        if not Path(pfile).exists:
            raise Exception(f"parm7 file {pfile} in structure '{name}' does not exist")
        
        p = parmed.load_file(pfile,structure=True)
        crds = self.data["positions"]
        for i,a in enumerate(p.atoms):
            a.xx = crds[i][0]
            a.xy = crds[i][1]
            a.xz = crds[i][2]
        return p
        

    def GetParmedAtoms(self):
        """
        Return a copy of the molecule using the parmed Structure class

        Parameters
        ----------
        None
        
        Returns
        -------
        mol : parmed Structure object
        """
        
        import parmed as pmd
        from parmed.structure import Structure
        from parmed.topologyobjects import Atom, Bond, Residue
        from . constants import GetAtomicNumber

        
        eles  = self.data["elements"]
        types = self.data["types"]
        qs    = self.data["charges"]
        #q     = self.data["charge"]
        q     = self.GetCharge()
        crds  = self.data["positions"]
        bonds = self.data["bonds"]
        
        # Pull your residue arrays
        if "residxs" in self.data:
            res_indices = self.data["residxs"]    # Array of integer residue indices per atom
        else:
            res_indices = [0] * len(eles)
            
        if "resnames" in self.data:
            res_names_dict = self.data["resnames"]  # Dict mapping int indices to str names
        else:
            res_names_dict = { 0: "MOL" }
        
        if "names" in self.data:
            names = self.data["names"]
        else:
            names = eles


            
        mol = Structure()
        alist = []
        for i in range(len(eles)):
            z = GetAtomicNumber(eles[i])
            a = Atom(name=names[i],type=types[i],
                     atomic_number=z,charge=qs[i])
            a.xx = crds[i][0]
            a.xy = crds[i][1]
            a.xz = crds[i][2]
            alist.append(a)

            # 1. Grab the specific residue integer index for this specific atom
            res_idx = res_indices[i]
            
            # 2. Extract the matching residue string name (fallback to 'MOL' if missing)
            res_name = res_names_dict.get(res_idx, "MOL")
            
            mol.add_atom(a,resname=res_name, resnum=res_idx+1)
            
        for x in bonds:
            mol.bonds.append(pmd.Bond(alist[x[0]],alist[x[1]]))
            
        return mol

    
    def GetASEAtoms(self):
        """
        Return a copy of the molecule using the ASE molecule class

        Parameters
        ----------
        None
        
        Returns
        -------
        atoms : ASE Atoms object
        """
        import numpy as np
        import ase
        
        crds = np.array(self.data["positions"])
        eles = self.data["elements"]
        #q    = self.data["charge"]
        q    = self.GetCharge()
        m    = self.data["spin"]
        qs   = self.data["charges"]
        atlist = "".join( ["%s1"%(ele) for ele in eles ] )

        atoms = ase.Atoms(atlist,positions=crds,charges=qs)
        atoms.info["charge"] = q
        atoms.info["spin"] = m
        atoms.calc = None

        return atoms

    
    # def GetRDKitAtoms(self):
    #     """
    #     Return a copy of the molecule using the RDKit molecule class

    #     Parameters
    #     ----------
    #     None
        
    #     Returns
    #     -------
    #     mol : RDKit molecule
    #     """
    #     from rdkit.Chem import MolFromMol2Block
    #     from rdkit import rdBase
    #     from rdkit.Chem import SanitizeMol
    #     from rdkit.Chem import GetFormalCharge
    #     from rdkit.Chem import rdDetermineBonds
    #     from io import StringIO

    #     mol = self.GetParmedAtoms()
    #     for i,a in enumerate(mol.atoms):
    #         a.type = self.data["elements"][i]
            
    #     rdBase.DisableLog('rdApp.warning')
    #     rdBase.DisableLog('rdApp.error')

    #     mol2str = StringIO()
    #     mol.save(mol2str,format="MOL2")
    #     mol2str = mol2str.getvalue()
    #     mol = MolFromMol2Block(mol2str, removeHs=False, sanitize=False )

    #     for atom in mol.GetAtoms():
    #         atom.SetFormalCharge(0)
    #     rdDetermineBonds.DetermineBondOrders(mol, charge=int(round(self.data["charge"])))
        
    #     SanitizeMol(mol)
    #     rdBase.EnableLog('rdApp.warning')
    #     rdBase.EnableLog('rdApp.error')
    #     #print("mol2str=\n",mol2str)
    #     #print("Formal charge=",GetFormalCharge(mol))
    #     return mol

    
    def GetRDKitAtoms(self):
        """
        Return a copy of the molecule using the RDKit molecule class

        Parameters
        ----------
        None
        
        Returns
        -------
        mol : RDKit molecule
        """
        from rdkit.Chem import MolFromMol2Block
        from rdkit import rdBase
        from rdkit.Chem import SanitizeMol
        from rdkit.Chem import GetFormalCharge
        from rdkit.Chem import rdDetermineBonds
        from rdkit.Chem import AtomPDBResidueInfo # <-- Import the metadata class
        from io import StringIO

        mol = self.GetParmedAtoms()
        for i,a in enumerate(mol.atoms):
            a.type = self.data["elements"][i]
            
        rdBase.DisableLog('rdApp.warning')
        rdBase.DisableLog('rdApp.error')

        mol2str = StringIO()
        mol.save(mol2str,format="MOL2")
        mol2str = mol2str.getvalue()
        mol = MolFromMol2Block(mol2str, removeHs=False, sanitize=False )

        for atom in mol.GetAtoms():
            atom.SetFormalCharge(0)
        rdDetermineBonds.DetermineBondOrders(mol, charge=self.GetCharge())
        
        SanitizeMol(mol)
        rdBase.EnableLog('rdApp.warning')
        rdBase.EnableLog('rdApp.error')

        # --- Inject Residue Information into the final RDKit Molecule ---
        eles = self.data["elements"]
        res_indices = self.data.get("residxs", [0] * len(eles))
        res_names_dict = self.data.get("resnames", {0: "MOL"})
        names = self.data.get("names", eles)

        for i, atom in enumerate(mol.GetAtoms()):
            # 1. Gather raw data matching this atom's order index
            atom_name = names[i]
            res_idx = int(res_indices[i])
            res_name = res_names_dict.get(res_idx, "MOL")
            res_num = res_idx + 1 # Convert to 1-indexed for structural file formats

            # 2. Instantiate RDKit's structural record container
            res_info = AtomPDBResidueInfo(
                atomName=atom_name.ljust(4), # Standard PDB atom names are 4-chars wide
                residueName=res_name[:3].upper(), # Keeps it standardized to PDB (3 chars max)
                residueNumber=res_num,
                chainId="A" # Default chain assignment since MOL2/Arrays lack it
            )

            # 3. Permanently bind the residue attributes onto the RDKit atom 
            atom.SetMonomerInfo(res_info)

        return mol


    def Update(self,ene,crds,frcs):
        """
        Set the energy, positions, and forces

        Parameters
        ----------
        ene : float
            Energy in eV

        crds : list of list or N,3 numpy array
            The atomic coordinates in Angstrom.
            This will be internally converted to plain lists.

        frcs : list of list or N,3 numpy array, optional
            The atomic forces in eV/Angstrom.
            If forces are unavailable, set to None

        Returns
        -------
        None
        """
        self.data["energy"] = ene
        try:
            self.data["positions"] = crds.tolist()
        except:
            self.data["positions"] = crds
        self.data["forces"] = None
        if frcs is not None:
            try:
                self.data["forces"] = frcs.tolist()
            except:
                self.data["forces"] = frcs


    def SaveCrds(self,fname_or_fh,fmt=None):
        """
        Save structure to file. Format is inferred from name,
        but format can be manually specified.

        Parameters
        ----------
        fname_or_fh : str or file-handle
            Writes structure to the opened file-handle or
            it overwrites the specified filename.
        fmt : str, default=None
            File format. If None, the format is determined
            from the filename suffix. Supported formats:
        
            Suffix   fmt   Type
            .xyz     XYZ   ASE extended xyz format
            .mol2    MOL2  Tripos mol2 format
            .rst7    RST7  Amber formatted restart
            .pdb     PDB   Protein Data Bank format

        Returns
        -------
        None
        """
        
        from pathlib import Path
        import ase.io
        import numpy as np

        import parmed as pmd
        from parmed.structure import Structure
        from parmed.topologyobjects import Atom, Bond, Residue
        from . constants import GetAtomicNumber
        
        eles  = self.data["elements"]
        types = self.data["types"]
        qs    = self.data["charges"]
        #q     = self.data["charge"]
        q     = self.GetCharge()
        crds  = self.data["positions"]
        bonds = self.data["bonds"]

        if hasattr(fname_or_fh, 'read') or hasattr(fname_or_fh, 'write'):
            if fmt is None:
                raise Exception("Expected fmt because fname_or_fh is a file descriptor")
            fh = fname_or_fh
        else:
            suffix = Path(fname_or_fh).suffix
            if suffix == ".xyz":
                fmt="XYZ"
                fh = fname_or_fh
            elif suffix == ".mol2":
                fmt="MOL2"
                fh = fname_or_fh
            elif suffix == ".rst7":
                fmt="RST7"
                fh = open(fname_or_fh,"w")
            elif suffix == ".pdb":
                fmt="PDB"
                fh = open(fname_or_fh,"w")
            else:
                raise Exception(f"Unknown suffix {suffix}")
        fmt = fmt.upper()
        if fmt == "XYZ":
            atoms = self.GetASEAtoms()
            ase.io.write(fh,atoms,format="extxyz")
        elif fmt == "MOL2":
            # mol = Structure()
            # alist = []
            # for i in range(len(eles)):
            #     z = GetAtomicNumber(eles[i])
            #     a = Atom(name=eles[i],type=types[i],
            #              atomic_number=z,charge=qs[i])
            #     a.xx = crds[i][0]
            #     a.xy = crds[i][1]
            #     a.xz = crds[i][2]
            #     alist.append(a)
            #     mol.add_atom(a,resname='MOL', resnum=1)
            # for x in bonds:
            #     mol.bonds.append(pmd.Bond(alist[x[0]],alist[x[1]]))
            mol = self.GetParmedAtoms()
            mol.save(fh,overwrite=True,format="MOL2")
        elif fmt == "RST7":
            crds = np.array(crds)
            #fh = open(fname,"w")
            write_amber_restart(crds, fh)
            #fh.close()
        elif fmt == "PDB":
            mol = self.GetParmedAtoms()
            mol.save(fh,overwrite=True,format="PDB")
        else:
            raise Exception(f"Unknown format {fmt}")

    def GetGraph(self):
        """Return the cached covalent GraphSearch (read-only for RotateMask).

        Callers that only need masks / path queries must not mutate the graph.
        """
        from . AmberParm import bonds2graph
        if self.graph is None:
            self.graph = bonds2graph(self.data["bonds"])
        return self.graph

    
    def GetFunctionalGroups(self):
        """
        Get a dict of functional groups in this molecule and the
        corresponding sets of atom indexes

        Parameters
        ----------
        None
        
        Returns
        -------
        fg : dict of list of tuple
            key: str, functional group name
            value: list of dict, each element is a distinct
                 functional group.  The tuple is a set of
                 atom indexes
        """
        #from . ChemFG_Tool.ChemFG_Tool import GetFunctionalGroups
        #return GetFunctionalGroups( self.GetRDKitAtoms() )
        from . FindFuncGrps import FindFuncGrps_from_rdkit
        return FindFuncGrps_from_rdkit( self.GetRDKitAtoms() )

    
    def GetFunctionalGroupCharges(self):
        """
        Get a dict of functional group charges

        Parameters
        ----------
        None

        Returns
        -------
        fgq : dict of list of float
             key: str, functional group name
             value: list of dict, each element is a distinct
                 functional group. The float is the sum of
                 atomic charges within the functional group.
        """
        from collections import defaultdict as ddict
        fg = self.GetFunctionalGroups()
        fgq = ddict(list)
        for key in fg:
            fgq[key] = [ self.GetChargeSum(idxs)
                         for idxs in fg[key] ]
        return fgq

    
    def GetChargeSum(self,idxs):
        """
        Get the sum of selected atomic charges

        Parameters
        ----------
        idxs : list of int
            The 0-based atom indexes

        Returns
        -------
        sumqs : float
            The net partial sum of atomic charges
        """
        qs = [ self.data["charges"][idx] for idx in idxs ]
        return sum(qs)


    # def GetEspalomaCharges(self):
    #     import sys
    #     from types import ModuleType

    #     # Create a dummy blank module structure
    #     fake_graphbolt = ModuleType('dgl.graphbolt')
    #     fake_graphbolt.__path__ = []

    #     # Inject it directly into Python's active system memory cache
    #     sys.modules['dgl.graphbolt'] = fake_graphbolt

    #     # Now override your PyTorch pickler settings
    #     import torch
    #     from functools import partial
    #     torch.load = partial(torch.load, weights_only=False)

    #     # Safely import your frameworks without hitting the C++ crash line
    #     from rdkit import Chem
    #     from espaloma_charge import charge
        
    #     #molecule = Chem.MolFromSmiles("N#N")
    #     molecule = self.GetRDKitAtoms()
    #     return charge(molecule)


    def GetHilfikerCharges(self):
        from . RespFit import hilfiker_charges
        atoms = self.GetASEAtoms()
        q = int(round(sum(self.data["charges"])))
        return hilfiker_charges(atoms,total_charge=q)

    
    def GetEspalomaCharges(self):
        import sys
        import warnings
        from types import ModuleType
        from functools import partial
        import torch
        import rdkit.rdBase as rdb
        from . RespFit import espaloma_charge

        # 1. Suppress Python-level warnings
        warnings.filterwarnings("ignore", category=UserWarning, module="torchdata")
        warnings.filterwarnings("ignore", message=".*Recommend creating graphs.*")

        # 2. Inject dummy graphbolt structure into cache if not present
        if 'dgl.graphbolt' not in sys.modules:
            fake_graphbolt = ModuleType('dgl.graphbolt')
            fake_graphbolt.__path__ = []
            sys.modules['dgl.graphbolt'] = fake_graphbolt

        # 3. Override PyTorch pickler settings for legacy model unpickling
        torch.load = partial(torch.load, weights_only=False)

        # 4. Safely import your frameworks inside the function context
        from rdkit import Chem
        from rdkit.Chem import rdDetermineBonds
        from espaloma_charge import charge
        
        molecule = self.GetRDKitAtoms()
        #print("Total charge:", Chem.GetFormalCharge(molecule))
        #print("Expected charge:",int(round(self.data["charge"])))
        
        # 5. Temporarily silence RDKit C++ streams only during the charge call
        # This protects the rest of your ffpopt pipeline's error visibility
        rdb.DisableLog('rdApp.warning')
        rdb.DisableLog('rdApp.error')
        rdb.DisableLog('rdApp.info')

        try:
            charges = espaloma_charge(molecule,total_charge=self.GetCharge())
        finally:
            # 6. Re-enable the C++ log streams before control exits the method
            rdb.EnableLog('rdApp.warning')
            rdb.EnableLog('rdApp.error')
            rdb.EnableLog('rdApp.info')

        #print("sum=",sum(charges))
            
        return charges

    
    def set_dihedral(self,a,b,c,d,value):
        #import numpy as np
        from . Constraints import Constraint
        atoms = self.GetASEAtoms()
        #initial = self.get_dihedral(a,b,c,d)
        con = Constraint("dihed",[a,b,c,d],
                         value=value,
                         graph=self.GetGraph())
        #print(atoms.get_dihedral(a,b,c,d))
        atoms = con.modify(atoms)
        #print(atoms.get_dihedral(a,b,c,d))
        self.Update(0,atoms.get_positions(),None)
        #final = self.get_dihedral(a,b,c,d)
        #print("inital/final/target = %8.3f %8.3f %8.3f"\
        #      %(initial,final,value))
        #exit(0)
        
    
    #
    # These mimic methods of an ASE Atoms object
    #
    
    def get_dihedral(self,a,b,c,d):
        """Return dihedral angle in degrees"""
        return self.GetASEAtoms().get_dihedral(a,b,c,d)

    def get_angle(self,a,b,c):
        """Return angle in degrees"""
        return self.GetASEAtoms().get_angle(a,b,c)

    def get_distance(self,a,b):
        """Return distance in Angstrom"""
        return self.GetASEAtoms().get_distance(a,b)

    def get_potential_energy(self):
        """Return energy in eV"""
        return self.data["energy"]

    def get_forces(self):
        """Return N,3 numpy array of atomic forces in eV/Angstrom"""
        import numpy as np
        return np.array(self.data["forces"])

    def get_positions(self):
        """Return N,3 numpy array of atomic coordinates in Angstrom"""
        import numpy as np
        return np.array(self.data["positions"])

    def copy(self):
        """Returns of deepcopy of this Struct"""
        import copy
        return copy.deepcopy(self)

    
class ListOfStruct(object):
    
    SANDERMODES=["SANDER","DFTB3","DFTB2","AM1D"]
    
    def __init__(self,structs):
        from copy import deepcopy

        if isinstance(structs, str):
            raise TypeError(f"Expected a list or dict, but received a string: {structs!r}")
        
        self.structs = deepcopy(structs)
        self.args  = None
        self.calc  = None

        
    def __getstate__(self):
        import copy
        # Copy the object's state dictionary
        state = self.__dict__.copy()
        #print(state.keys())
        # Remove the specific attribute
        if 'calc' in state:
            #del state['calc']
            state['calc'] = None
        return state
        
    @classmethod
    def from_file(cls,filename):
        ss = None
        try:
            import json
            fh = open(filename,'r')
            data = json.load(fh)
            ss = [Struct(x) for x in data]
        except Exception as JsonError:
            try:
                ss = [ Struct.from_mol2(filename) ]
            except Exception as Mol2Error:
                raise Exception(JsonError)
        return cls( ss )

    

    def __iter__(self):
        return iter(self.structs)

    
    def __len__(self):
        return len(self.structs)

    
    def __setitem__(self, index, value):
        self.structs[index] = value

        
    def __getitem__(self, index):
        # This maps indexing directly to the list member
        return self.structs[index]

    
    def save(self, filename, indent=None):
        """Write structures as JSON. Default ``indent=None`` (compact)."""
        import json
        for x in self.structs:
            if x.data["constraints"] is None:
                x.data["constraints"] = []
        with open(filename, "w") as fh:
            json.dump([x.data for x in self.structs], fh, indent=indent)

    def clear_runtime_caches(self):
        """Drop live calculators / model caches before pickling checkpoints."""
        calc = getattr(self, "calc", None)
        if calc is not None:
            try:
                calc.reset()
            except Exception:
                pass
            self.calc = None
        if hasattr(self, "_ffpopt_calc_cache"):
            self._ffpopt_calc_cache = None


    def GetByName(self,name):
        keep = None
        for s in self.structs:
            if s.data["name"] == name:
                keep=s
                break
        return keep
        

        
    def SetArgs(self,args):
        from copy import deepcopy
        self.args = deepcopy(args)

        if hasattr(self.args,"cpu"):
            if self.args.cpu:
                import os
                os.environ['JAX_PLATFORMS'] = 'cpu'
                os.environ['CUDA_VISIBLE_DEVICES'] = '-1'

        geometric_kwargs = {}
        psi4_kwargs = {}

        if isinstance(args,dict):
            for key in ["coordsys","maxiter","converge","enforce"]:
                if key in args:
                    geometric_kwargs[key] = args[key]
            for key in ["memory","num_threads"]:
                if key in args:
                    geometric_kwargs[key] = args[key]
    
        else:
            try:
                geometric_kwargs = { "coordsys": str(args.geometric_coordsys),
                                     "maxiter": str(args.geometric_maxiter),
                                     "converge": str(args.geometric_converge),
                                     "enforce": str(args.geometric_enforce) }
            except:
                pass

            try:
                psi4_kwargs = { "memory": str(args.psi4_memory),
                                "num_threads": str(args.psi4_num_threads) }
            except:
                pass

        
        self.extra_args = { "geometric": geometric_kwargs,
                            "psi4": psi4_kwargs }

        #self.calc = self.BuildCalc(self.structs[0])
        self.calc = None

        
            
    def BuildCalc(self,struct,calc=None):
        from . ase.calculator import GenCalculator

        if calc is None:
            if self.calc is not None:
                if self.calc.parm == struct.data["parm"] and \
                   self.calc.spin == struct.data["spin"] and \
                   self.calc.charge == struct.GetCharge():
                    calc = self.calc
                    #print("CALC: reuse previous")

        model = None
        if calc is None:
            if isinstance(self.args,dict):
                if "psi4_memory" in self.args:
                    memory = self.args["psi4_memory"]
                else:
                    memory = "1gb"
                if "psi4_num_threads" in self.args:
                    num_threads = int(self.args["psi4_num_threads"])
                elif "num_threads" in self.args:
                    num_threads = int(self.args["num_threads"])
                else:
                    num_threads = 1
                    
                if "mfile" in self.args:
                    mfile = self.args["mfile"]
                else:
                    mfile = None
                if "model" in self.args:
                    model = self.args["model"]
            else:
                memory = getattr(self.args,"psi4_memory","1gb")
                num_threads = getattr(self.args,"psi4_num_threads",1)
                mfile = None
                if hasattr(self.args,"mfile"):
                    mfile = self.args.mfile
                model = "SANDER"
                if hasattr(self.args,"model"):
                    model = self.args.model
                
            kwargs = { "memory": memory,
                       "num_threads": num_threads,
                       "mfile": mfile }
            
            charge = struct.GetCharge()
            spin = struct.data["spin"]
            parm = struct.data["parm"]
            mode = model.upper()
            
            if mode in ListOfStruct.SANDERMODES:
                import tempfile
                import os
                import numpy as np
                from pathlib import Path
                
                tmpfile_loc = "./tmpfiles"
                if not Path(tmpfile_loc).is_dir():
                    os.makedirs(tmpfile_loc, exist_ok=True)

                fd, path = tempfile.mkstemp(dir=tmpfile_loc,suffix=".rst7")
                fh = os.fdopen(fd,'w')
                write_amber_restart( np.array(struct.data["positions"]), fh )
                fh.close()

                try:
                    import sander
                    sander.cleanup()
                except:
                    pass

                calc = GenCalculator(mode,charge,spin,parm,path,**kwargs)
                os.remove(path)
            else:
                calc = GenCalculator(mode,charge,spin,parm,None,**kwargs)
        self.calc = calc
        return calc

    
    def BuildRestrainedCalc(self,s,reslist=None):
        calc = self.BuildCalc(s)
        rcalc = calc

        res = None
        if reslist is not None:
            res = reslist
        elif s.restraints is not None:
            res = s.restraints
            
        if res is not None:
            from . ase.calculator import RestrainedCalculator
            rcalc = RestrainedCalculator(calc,res)
            
        return rcalc



from . ase.calculator import GenCalculator
from ase.calculators.calculator import Calculator,all_changes

class RestCalculator(GenCalculator):
    
    implemented_properties = ['energy','forces','free_energy']
    nolabel=True
    def __init__(self,mode,inp,**kwargs):
        los = ListOfStruct.from_file(inp)
        kwargs["model"] = mode.upper()
        #print("kwargs=",kwargs)
        los.SetArgs(kwargs)
        self.charge = los.structs[0].GetCharge()
        #print("kwargs=",kwargs)
        self.calc = los.BuildRestrainedCalc(los.structs[0])
        #print("kwargs=",kwargs)
        Calculator.__init__(self,**kwargs)

    def calculate(self,
                  atoms=None,
                  properties=None,
                  system_changes=all_changes):
        import numpy as np
        import ase
        if self.charge is not None:
            atoms.info["charge"] = self.charge
        if properties is None:
            properties = self.implemented_properties
        Calculator.calculate(self, atoms, properties, system_changes)
        atoms.calc =  self.calc
        energy = atoms.get_potential_energy()
        forces = atoms.get_forces()
        self.results['energy'] = energy
        self.results['free_energy'] = energy
        self.results['forces'] = forces




